# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-06-26 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0003_auto_20200621_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='RCTemplateCQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.CQuestion')),
                ('ctemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.CharacterTemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
