# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-03 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0004_rctemplatecquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField()),
                ('cquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.CQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Slams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slam_name', models.CharField(max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='slam',
            name='slam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.Slams'),
        ),
        migrations.AddField(
            model_name='slam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
