# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0005_auto_20200703_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='cquestion',
            field=models.TextField(),
        ),
    ]
