# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-05 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0006_auto_20200705_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slam',
            name='cquestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.CQuestion'),
        ),
    ]
