# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-05 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0007_auto_20200705_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlamChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr', to=settings.AUTH_USER_MODEL)),
                ('slam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.Slams')),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
