# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-05 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0008_slamchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='slamchart',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
