# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-05 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0009_slamchart_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slamchart',
            name='is_fr',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slamchart',
            name='is_to',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slamchart',
            name='mess',
            field=models.TextField(blank=True),
        ),
    ]
