# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-11 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0011_auto_20200711_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='mess',
            field=models.TextField(blank=True),
        ),
    ]
