# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0013_remove_answer_binary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='slamchar',
            new_name='slamchart',
        ),
    ]
