# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-11 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0015_slamchart_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slamchart',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
