# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-07-11 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0017_auto_20200711_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='mess',
        ),
        migrations.AddField(
            model_name='slamchart',
            name='rmess',
            field=models.TextField(blank=True),
        ),
    ]
