# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-08-21 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0018_auto_20200711_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slamchart',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
