# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-01 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0020_slamchart_isreadslam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giftname', models.CharField(max_length=32)),
            ],
        ),
    ]
