# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-06 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0022_userextension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='dob',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
