# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0022_userextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
