# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-21 23:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0023_userextension_pro_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifts',
            old_name='giftname',
            new_name='gift_name',
        ),
        migrations.AddField(
            model_name='gifts',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gifts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
