# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-09-24 00:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0024_auto_20200921_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('cquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.CQuestion')),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.Gifts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.BigIntegerField(blank=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('cquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.CQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='GiftChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('mess', models.TextField(blank=True)),
                ('rmess', models.TextField(blank=True)),
                ('giftmess', models.TextField(blank=True)),
                ('is_fr', models.BooleanField(default=True)),
                ('is_to', models.BooleanField(default=True)),
                ('is_re', models.BooleanField(default=True)),
                ('response', models.BooleanField(default=False)),
                ('isreadslam', models.BooleanField(default=False)),
                ('fr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfr', to=settings.AUTH_USER_MODEL)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.Gifts')),
                ('re', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gre', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='giftanswer',
            name='giftchart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.GiftChart'),
        ),
    ]
