# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-10-06 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0026_slam_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('rmess', models.TextField(blank=True)),
                ('is_to', models.BooleanField(default=True)),
                ('response', models.BooleanField(default=False)),
                ('isreadslam', models.BooleanField(default=False)),
                ('contrib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='giftchart',
            name='is_to',
        ),
        migrations.RemoveField(
            model_name='giftchart',
            name='isreadslam',
        ),
        migrations.RemoveField(
            model_name='giftchart',
            name='response',
        ),
        migrations.RemoveField(
            model_name='giftchart',
            name='rmess',
        ),
        migrations.RemoveField(
            model_name='giftchart',
            name='to',
        ),
        migrations.AddField(
            model_name='contributor',
            name='giftchart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slambook.GiftChart'),
        ),
    ]
