# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-11-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0028_group_user_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='giftchart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gc', to='slambook.GiftChart'),
        ),
    ]
