# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-11-27 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0029_auto_20201126_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='isreadslam',
            new_name='isreadgift',
        ),
    ]
